name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送以v开头的标签时触发

jobs:
  build:
    name: Build for ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            ext: ""
          - os: linux
            arch: arm64
            ext: ""
          - os: windows
            arch: amd64
            ext: ".exe"
          - os: windows
            arch: arm64
            ext: ".exe"
          - os: darwin
            arch: amd64
            ext: ""
          - os: darwin
            arch: arm64
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w" -o "SmsForwarder_tgbot-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}" .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmsForwarder_tgbot-${{ matrix.os }}-${{ matrix.arch }}
          path: SmsForwarder_tgbot-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SmsForwarder_tgbot-linux-amd64
            SmsForwarder_tgbot-linux-arm64
            SmsForwarder_tgbot-windows-amd64.exe
            SmsForwarder_tgbot-windows-arm64.exe
            SmsForwarder_tgbot-darwin-amd64
            SmsForwarder_tgbot-darwin-arm64
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 