name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送以v开头的标签时触发

jobs:
  build:
    name: Build for ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            ext: ""
          - os: linux
            arch: arm64
            ext: ""
          - os: windows
            arch: amd64
            ext: ".exe"
          - os: windows
            arch: arm64
            ext: ".exe"
          - os: darwin
            arch: amd64
            ext: ""
          - os: darwin
            arch: arm64
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w" -o "SmsForwarder_tgbot-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}" .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmsForwarder_tgbot-${{ matrix.os }}-${{ matrix.arch }}
          path: SmsForwarder_tgbot-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ## 构建版本
            
            ### Linux
            - **AMD64**: [SmsForwarder_tgbot-linux-amd64](https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/SmsForwarder_tgbot-linux-amd64)
            - **ARM64**: [SmsForwarder_tgbot-linux-arm64](https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/SmsForwarder_tgbot-linux-arm64)
            
            ### Windows
            - **AMD64**: [SmsForwarder_tgbot-windows-amd64.exe](https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/SmsForwarder_tgbot-windows-amd64.exe)
            - **ARM64**: [SmsForwarder_tgbot-windows-arm64.exe](https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/SmsForwarder_tgbot-windows-arm64.exe)
            
            ### macOS
            - **AMD64**: [SmsForwarder_tgbot-darwin-amd64](https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/SmsForwarder_tgbot-darwin-amd64)
            - **ARM64**: [SmsForwarder_tgbot-darwin-arm64](https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/SmsForwarder_tgbot-darwin-arm64)

      - name: Upload Linux AMD64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/SmsForwarder_tgbot-linux-amd64/SmsForwarder_tgbot-linux-amd64
          asset_name: SmsForwarder_tgbot-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Linux ARM64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/SmsForwarder_tgbot-linux-arm64/SmsForwarder_tgbot-linux-arm64
          asset_name: SmsForwarder_tgbot-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload Windows AMD64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/SmsForwarder_tgbot-windows-amd64/SmsForwarder_tgbot-windows-amd64.exe
          asset_name: SmsForwarder_tgbot-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Windows ARM64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/SmsForwarder_tgbot-windows-arm64/SmsForwarder_tgbot-windows-arm64.exe
          asset_name: SmsForwarder_tgbot-windows-arm64.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS AMD64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/SmsForwarder_tgbot-darwin-amd64/SmsForwarder_tgbot-darwin-amd64
          asset_name: SmsForwarder_tgbot-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS ARM64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/SmsForwarder_tgbot-darwin-arm64/SmsForwarder_tgbot-darwin-arm64
          asset_name: SmsForwarder_tgbot-darwin-arm64
          asset_content_type: application/octet-stream 